swagger: '2.0'
info:
  title: Depax back-end task
  version: 1.0.0
  description: new feature for suggestions 
  contact:
    email: 'm6abdelmonsef@gmail.com'
    website: 'https://github.com/mohamed-abdelmonsef'
  servers:
    -url: 'http://localhost:3000/'
    description: this is my local server
    -url: 'https://depax-blog.herokuapp.com/'
    description: this is my heroku server
schemes: [https ,http]   
produces:
  - application/json
consumes:
  - application/json

securityDefinitions:
  Bearer:
    type: apiKey
    name: x-access-token
    in: header
##############################################

tags:
  - name: Auth
  - name: Fake
  - name: Home 


############################################################################################
paths:

### registeration endpoint
  /register:
    put:
      summary: api for adding new user
      tags:
        - Auth
      parameters:
        - in: body
          name: user
          required: true
          description: user inputs
          schema:
            $ref: '#/components/schemas/userRegister'
      responses:
        201:
          description: the user registered successfully
          content:
            application/json:
              $ref: '#/components/schemas/userRegister'
        422:
          description: invalid data  
          content:
            application/json:
              $ref: '#/components/schemas/userRegister'
        500:
          description: db or server error (unexpected error)         

######### login api
  /login:
    post:
      summary: api for logging in
      tags:
        - Auth    
      parameters:
        - in: body
          name: user
          required: true
          description: user inputs
          schema:
            $ref: '#/components/schemas/userLogin'
      responses:
        200:
          description: the user logged in successfully
          content:
            application/json:
              $ref: '#/components/schemas/userLogin'
        401:
          description: invalid password
          content:      
            application/json:
              $ref: '#/components/schemas/userLogin'                
        404:
          description: user not found
          content:      
            application/json:
              $ref: '#/components/schemas/userLogin'
        422:
          description: invalid data  
          content:
            application/json:
              $ref: '#/components/schemas/userLogin'              
        500:
          description: db or server error (unexpected error)

########## endpoint that get suggestions
  /displaySuggestions/{articleId}:
    get:
      security:
        - Bearer: []
      summary: get suggestions
      tags:
        - Home
      parameters: 
        - in: path
          name: articleId
          required: true
          description: id of the article that user read now
          schema:
            type: string    
      responses:
        200:
          description: suggestions for user
        500:
          description: db or server error (unexpected error) 
        401:
          description: Unauthorized user    
        403:
          description: No token provided!


#### add fake articles endpoint
  /fakeArticles:
    post:
      security:
        - Bearer: []
      summary: api for add fake articles
      tags:
        - Fake
      parameters:
        - in: body
          name: inputs
          description: inputs of article
            schema:
              type: object
          schema:
            $ref: '#/components/schemas/article'
      responses:
        200:
          description: article added successfully
          content:
            application/json:
              $ref: '#/components/schemas/article'
        404:
          description: user not found or not exist anymore
        500:
          description: db or server error (unexpected error) 

############################################################################################
components:
  schemas:
### user registeration schema 
    userRegister:
      type: object
      required:
        - name
        - email
        - password
        - confirmPass
      properties:
        name:
          type: string
          description: name
        email:
          type: string
          description: user email
        password:
          type: string
          description: password must contain numbers
        confirmPass:
          type: string
          description: confirmation password
      example:
        name: momo
        email: mo@gmail.com
        password: aa1
        confirmPass: aa1        

#### user login schema
    userLogin:
      type: object
      required:
        - email
        - password
      properties: 
        email:
          type: string
          description: user email
        password:
          type: string
          description: password must contain numbers
      example:
        email: mo@gmail.com
        password: aa1

## article schema
    article:
      type: object
      properties: 
        name:
          type: string
          description: name of article 
        categories:
          type: array  
          description: categories of article 
      example:
        name: die hard
        categories: [action]







